### PR TITLE
Added projects section to showcase the projects

### PR DESCRIPTION
**Pull request by naveennamani**
By using title, description, tags and GitHub links in data.projects, the projects will be shown in a card format with stars and fork buttons

### CODE REVIEW

**Comment by BraydenTW** [comment]
Hey @naveennamani there was an error in build. 

`FaExternalLinkSquareAlt` is defined but never used. Could you fix that along with other errors potentially in the code?

Thanks.

**Review by BraydenTW — APPROVED** [review]

**Comment by BraydenTW** [comment]
Lgtm!

**Comment by naveennamani** [comment]
Hey, thanks for the corrections, I didn't think warning will lead to deployment failure, and I totally forget about the unused var. Can you please add the hacktoberfest-accepted label? Thanks.

**Comment by BraydenTW** [comment]
Sure - thanks again!

**Pull request merged**
